[project]
name = "sparql-notebook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "kurra>=1.5.9",
    "notebook>=7.4.2",
    "rdflib>=7.4.0",
    "isodate==0.7.2",
    "timefuncs>=0.1.4",
    "ipython==9.7.0",
]
